PRESCRIPTIONS = {
    "sadness": {
        "name": "Melancholy Relief",
        "emoji": "\U0001f31e",
        "description": "Gentle films that understand your sadness and help you heal",
        "movies": [
            {"title": "The Pursuit of Happyness", "year": 2006, "reason": "A story of resilience that reminds you pain is temporary"},
            {"title": "Inside Out", "year": 2015, "reason": "Teaches that sadness is a valid and necessary emotion"},
            {"title": "Good Will Hunting", "year": 1997, "reason": "Healing through connection and letting go of the past"},
            {"title": "Forrest Gump", "year": 1994, "reason": "Life's beauty in simplicity and perseverance"},
            {"title": "The Shawshank Redemption", "year": 1994, "reason": "Hope is the greatest escape from any prison"},
            {"title": "A Beautiful Day in the Neighborhood", "year": 2019, "reason": "Kindness as a healing force"},
            {"title": "Coco", "year": 2017, "reason": "Remembering loved ones with joy not sorrow"},
            {"title": "Up", "year": 2009, "reason": "Grief and adventure go hand in hand"},
            {"title": "The Secret Life of Walter Mitty", "year": 2013, "reason": "Escape the ordinary and find yourself"},
            {"title": "It's a Wonderful Life", "year": 1946, "reason": "Your existence matters more than you know"},
            {"title": "Perks of Being a Wallflower", "year": 2012, "reason": "We accept the love we think we deserve"},
            {"title": "Little Miss Sunshine", "year": 2006, "reason": "A broken family finding joy in imperfection"},
            {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "reason": "Even painful memories are worth keeping"},
            {"title": "Silver Linings Playbook", "year": 2012, "reason": "Finding light in mental health struggles"},
            {"title": "The Fault in Our Stars", "year": 2014, "reason": "Love and loss in the face of mortality"},
            {"title": "About Time", "year": 2013, "reason": "Appreciating ordinary moments before they pass"},
            {"title": "Big Fish", "year": 2003, "reason": "Stories heal the distance between father and son"},
            {"title": "The Intouchables", "year": 2011, "reason": "Friendship that transcends boundaries"},
            {"title": "Wonder", "year": 2017, "reason": "Choose kindness even when the world is harsh"},
            {"title": "Soul", "year": 2020, "reason": "Finding purpose in simply living"},
        ],
        "series": [
            {"title": "After Life", "reason": "Ricky Gervais navigating grief with dark humor"},
            {"title": "The Good Place", "reason": "What makes a good person? A philosophical journey"},
            {"title": "Ted Lasso", "reason": "Unstoppable optimism in the face of darkness"},
            {"title": "This Is Us", "reason": "Every family has pain, but love carries through"},
            {"title": "BoJack Horseman", "reason": "Raw look at depression and the path to healing"},
        ],
    },
    "anxiety": {
        "name": "Anxiety Soother",
        "emoji": "\U0001f30a",
        "description": "Calming stories that quiet the mind and ease tension",
        "movies": [
            {"title": "Amélie", "year": 2001, "reason": "Finding joy in life's small beautiful moments"},
            {"title": "My Neighbor Totoro", "year": 1988, "reason": "Pure childhood wonder and gentle comfort"},
            {"title": "Spirited Away", "year": 2001, "reason": "Finding courage in strange new worlds"},
            {"title": "The Princess Bride", "year": 1987, "reason": "Fairy tale comfort with wit and heart"},
            {"title": "Paddington 2", "year": 2017, "reason": "Pure kindness makes the world better"},
            {"title": "Chef", "year": 2014, "reason": "Doing what you love heals the soul"},
            {"title": "The Grand Budapest Hotel", "year": 2014, "reason": "Visually soothing storytelling at its finest"},
            {"title": "Julie & Julia", "year": 2009, "reason": "Finding purpose through cooking and passion"},
            {"title": "Kiki's Delivery Service", "year": 1989, "reason": "Burnout recovery through rest and community"},
            {"title": "Sing Street", "year": 2016, "reason": "Music as an escape from anxiety"},
            {"title": "Fantastic Mr. Fox", "year": 2009, "reason": "Whimsical stop-motion comfort"},
            {"title": "The Hundred-Foot Journey", "year": 2014, "reason": "Culture clash resolved through food and art"},
            {"title": "Hunt for the Wilderpeople", "year": 2016, "reason": "Adventure therapy in the New Zealand bush"},
            {"title": "Lilo & Stitch", "year": 2002, "reason": "Found family and 'ohana means nobody gets left behind"},
            {"title": "Howl's Moving Castle", "year": 2004, "reason": "Finding confidence when you feel invisible"},
            {"title": "Begin Again", "year": 2013, "reason": "Music heals broken hearts and anxious minds"},
            {"title": "WALL-E", "year": 2008, "reason": "Gentle romance in a chaotic world"},
            {"title": "The Muppet Movie", "year": 2011, "reason": "Silly joyful comfort that makes you smile"},
            {"title": "Eat Pray Love", "year": 2010, "reason": "Self-discovery across the world"},
            {"title": "Ocean's Eleven", "year": 2001, "reason": "Cool, confident fun that distracts the mind"},
        ],
        "series": [
            {"title": "Joe Pera Talks with You", "reason": "The calmest show ever made. Pure ASMR comfort"},
            {"title": "Bob's Burgers", "reason": "Wholesome family chaos that reduces anxiety"},
            {"title": "The Office (US)", "reason": "Familiar comforting humor for anxious days"},
            {"title": "Midnight Diner", "reason": "Japanese late-night food and human connection"},
            {"title": "Great British Baking Show", "reason": "Gentle competition and baked goods soothe nerves"},
        ],
    },
    "stress": {
        "name": "Stress Melter",
        "emoji": "\U0001f9d8",
        "description": "Escape into worlds that let your mind breathe",
        "movies": [
            {"title": "The Lord of the Rings: The Fellowship of the Ring", "year": 2001, "reason": "Epic escape into a richly detailed world"},
            {"title": "Interstellar", "year": 2014, "reason": "Perspective-expanding journey beyond our problems"},
            {"title": "The Martian", "year": 2015, "reason": "Problem-solving under pressure with optimism"},
            {"title": "La La Land", "year": 2016, "reason": "Dreams and love in a beautifully colored world"},
            {"title": "Moonrise Kingdom", "year": 2012, "reason": "Young love and adventure on a New England island"},
            {"title": "Ratatouille", "year": 2007, "reason": "Anyone can cook. Anyone can find their passion"},
            {"title": "The Life Aquatic with Steve Zissou", "year": 2004, "reason": "Quirky ocean adventure that dissolves stress"},
            {"title": "Zootopia", "year": 2016, "reason": "Determination in a vibrant animal world"},
            {"title": "School of Rock", "year": 2003, "reason": "Letting loose and finding your inner rockstar"},
            {"title": "The Terminal", "year": 2004, "reason": "Making the best of unexpected circumstances"},
            {"title": "Captain Fantastic", "year": 2016, "reason": "Alternative living and family bonds"},
            {"title": "Dazed and Confused", "year": 1993, "reason": "A chill hangout movie with no real plot pressure"},
            {"title": "The Beach", "year": 2000, "reason": "Paradise escape and self-discovery"},
            {"title": "Best in Show", "year": 2000, "reason": "Mockumentary comedy that requires zero brain power"},
            {"title": "The Darjeeling Limited", "year": 2007, "reason": "Train journey through India as therapy"},
            {"title": "Tampopo", "year": 1985, "reason": "Ramen western that's pure comfort food cinema"},
            {"title": "My Life as a Zucchini", "year": 2016, "reason": "Stop-motion sweetness about overcoming hardship"},
            {"title": "Paterson", "year": 2016, "reason": "Quiet daily life of a bus driver poet"},
            {"title": "The Secret Garden", "year": 1993, "reason": "Nature heals grief and transforms lives"},
            {"title": "Chocolat", "year": 2000, "reason": "Chocolate and kindness change a rigid town"},
        ],
        "series": [
            {"title": "Planet Earth II", "reason": "Nature's grandeur puts problems in perspective"},
            {"title": "Bluey", "reason": "Children's show with profound emotional intelligence"},
            {"title": "Brooklyn Nine-Nine", "reason": "Fast comedy that demands nothing but laughs"},
            {"title": "Parks and Recreation", "reason": "Wholesome government comedy that lifts spirits"},
            {"title": "Mushi-Shi", "reason": "Anime that's meditation in visual form"},
        ],
    },
    "heartbreak": {
        "name": "Heartbreak Healer",
        "emoji": "\u2764\ufe0f\u200d\U0001fa79",
        "description": "Stories that validate your pain and remind you of love's beauty",
        "movies": [
            {"title": "500 Days of Summer", "year": 2009, "reason": "A non-linear look at love and expectations"},
            {"title": "Before Sunrise", "year": 1995, "reason": "Connection that transcends time"},
            {"title": "Her", "year": 2013, "reason": "Love in unexpected places teaches us about ourselves"},
            {"title": "Casablanca", "year": 1942, "reason": "Classic sacrifice and the many forms of love"},
            {"title": "Lost in Translation", "year": 2003, "reason": "Two lonely souls finding each other in Tokyo"},
            {"title": "Marriage Story", "year": 2019, "reason": "Parting with love even when it ends"},
            {"title": "Blue Valentine", "year": 2010, "reason": "Love fades but the moments mattered"},
            {"title": "In the Mood for Love", "year": 2000, "reason": "Unspoken love in beautiful restrained frames"},
            {"title": "Brooklyn", "year": 2015, "reason": "Choosing love and home across continents"},
            {"title": "Carol", "year": 2015, "reason": "Forbidden love pursued with courage"},
            {"title": "The Holiday", "year": 2006, "reason": "Home exchange leads to unexpected healing"},
            {"title": "Under the Tuscan Sun", "year": 2003, "reason": "Rebuilding life after divorce in Italy"},
            {"title": "Call Me by Your Name", "year": 2017, "reason": "Summer love that changes you forever"},
            {"title": "Annie Hall", "year": 1977, "reason": "Love is irrational and we do it anyway"},
            {"title": "Punch-Drunk Love", "year": 2002, "reason": "Anxious love finds its match"},
            {"title": "Singin' in the Rain", "year": 1952, "reason": "Pure joy as the best medicine for heartache"},
            {"title": "The Lunchbox", "year": 2013, "reason": "Mumbai lunchbox connects two lonely hearts"},
            {"title": "Past Lives", "year": 2023, "reason": "What ifs and the lives we leave behind"},
            {"title": "A Star is Born", "year": 2018, "reason": "Love and loss in the spotlight"},
            {"title": "Like Crazy", "year": 2011, "reason": "Long distance love and its beautiful fractures"},
        ],
        "series": [
            {"title": "Fleabag", "reason": "Grief and love wrapped in sharp comedy"},
            {"title": "Normal People", "reason": "Intimate look at young love and miscommunication"},
            {"title": "Master of None", "reason": "Modern love and finding yourself"},
            {"title": "Gilmore Girls", "reason": "Fast-talking comfort for a broken heart"},
            {"title": "Insecure", "reason": "Modern relationships explored with honesty"},
        ],
    },
    "loneliness": {
        "name": "Connection Therapy",
        "emoji": "\U0001f30d",
        "description": "Stories that remind you you're never truly alone",
        "movies": [
            {"title": "Cast Away", "year": 2000, "reason": "Isolation and the human need for connection"},
            {"title": "WALL-E", "year": 2008, "reason": "Even in solitude, love finds a way"},
            {"title": "The Terminal", "year": 2004, "reason": "Building community wherever you land"},
            {"title": "Taxi Driver", "year": 1976, "reason": "Dark look at isolation and the need to belong"},
            {"title": "Into the Wild", "year": 2007, "reason": "Solitude's beauty and its limits"},
            {"title": "Swiss Army Man", "year": 2016, "reason": "A friendship between a man and a corpse. Strangely beautiful"},
            {"title": "Lars and the Real Girl", "year": 2007, "reason": "A community's love heals profound loneliness"},
            {"title": "Robot & Frank", "year": 2012, "reason": "Friendship with a robot in old age"},
            {"title": "Amélie", "year": 2001, "reason": "Connecting with others from behind the scenes"},
            {"title": "Yes Man", "year": 2008, "reason": "Saying yes to life opens doors to people"},
            {"title": "The Perks of Being a Wallflower", "year": 2012, "reason": "Finding your people changes everything"},
            {"title": "Groundhog Day", "year": 1993, "reason": "Stuck in a loop until you connect with others"},
            {"title": "The Breakfast Club", "year": 1985, "reason": "Five strangers discover they're not so different"},
            {"title": "Short Term 12", "year": 2013, "reason": "Healing others heals yourself"},
            {"title": "Tokyo Story", "year": 1953, "reason": "Family distance and the quiet ache of aging"},
            {"title": "The Before Trilogy", "year": 1995, "reason": "Two people talking is all the connection we need"},
            {"title": "Harold and Maude", "year": 1971, "reason": "Unlikely friendship that transcends age"},
            {"title": "The Station Agent", "year": 2003, "reason": "Finding friendship in an abandoned train depot"},
            {"title": "Babyteeth", "year": 2019, "reason": "Connection blooms in unexpected circumstances"},
            {"title": "Me Before You", "year": 2016, "reason": "Love transforms even the shortest time"},
        ],
        "series": [
            {"title": "The End of the F***ing World", "reason": "Two outsiders find each other on the road"},
            {"title": "Russian Doll", "reason": "Stuck in a loop until you connect deeply"},
            {"title": "Bojack Horseman", "reason": "The loneliness of fame and the search for meaning"},
            {"title": "The Office", "reason": "Workplace family for lonely days"},
            {"title": "Community", "reason": "A study group becomes a found family"},
        ],
    },
    "anger": {
        "name": "Anger Release",
        "emoji": "\U0001f4a5",
        "description": "Cathartic stories that channel rage into understanding",
        "movies": [
            {"title": "Fight Club", "year": 1999, "reason": "Channeling modern frustration into something real"},
            {"title": "The Matrix", "year": 1999, "reason": "Anger at the system. Red pill or blue pill"},
            {"title": "V for Vendetta", "year": 2005, "reason": "Righteous anger against oppression"},
            {"title": "John Wick", "year": 2014, "reason": "Pure cathartic action with emotional depth"},
            {"title": "Gladiator", "year": 2000, "reason": "Honor and vengeance in ancient Rome"},
            {"title": "Taken", "year": 2008, "reason": "Parental fury with a very particular set of skills"},
            {"title": "The Dark Knight", "year": 2008, "reason": "Anger and chaos vs order and justice"},
            {"title": "Kill Bill Vol 1", "year": 2003, "reason": "Revenge as art"},
            {"title": "Office Space", "year": 1999, "reason": "Therapeutic comedy about workplace rage"},
            {"title": "Falling Down", "year": 1993, "reason": "A man's breaking point in modern society"},
            {"title": "Death Wish", "year": 1974, "reason": "Vigilante justice as fantasy release"},
            {"title": "Mad Max: Fury Road", "year": 2015, "reason": "Two hours of pure kinetic rage and redemption"},
            {"title": "Uncut Gems", "year": 2019, "reason": "Anxiety-inducing but cathartic release"},
            {"title": "Birdman", "year": 2014, "reason": "Creative frustration and ego battles"},
            {"title": "Whiplash", "year": 2014, "reason": "Fury channeled into artistic excellence"},
            {"title": "Network", "year": 1976, "reason": "I'm mad as hell and I'm not going to take it anymore"},
            {"title": "Three Billboards Outside Ebbing, Missouri", "year": 2017, "reason": "Grief-fueled anger finds unexpected resolution"},
            {"title": "The Godfather", "year": 1972, "reason": "Revenge and power as family business"},
            {"title": "Oldboy", "year": 2003, "reason": "The ultimate revenge tragedy"},
            {"title": "A Clockwork Orange", "year": 1971, "reason": "Violence and free will in a controlled world"},
        ],
        "series": [
            {"title": "Breaking Bad", "reason": "Walter White's transformation is pure channeled rage"},
            {"title": "Mr. Robot", "reason": "Anger at the system fuels a revolution"},
            {"title": "Sons of Anarchy", "reason": "Brotherhood and vengeance on two wheels"},
            {"title": "The Punisher", "reason": "Grief and anger turned to justice"},
            {"title": "Ozark", "reason": "Frustration and survival in impossible circumstances"},
        ],
    },
    "burnout": {
        "name": "Rest & Recovery",
        "emoji": "\U0001f634",
        "description": "Gentle stories about rest, renewal, and finding your rhythm",
        "movies": [
            {"title": "Office Space", "year": 1999, "reason": "The ultimate anti-work comedy"},
            {"title": "Kiki's Delivery Service", "year": 1989, "reason": "Burnout is real. Rest is necessary"},
            {"title": "Why Don't You Play in Hell?", "year": 2013, "reason": "Creative passion over everything"},
            {"title": "Stranger Than Fiction", "year": 2006, "reason": "Breaking free from routine to live fully"},
            {"title": "The Secret Life of Walter Mitty", "year": 2013, "reason": "Quit the desk and see the world"},
            {"title": "Chef", "year": 2014, "reason": "Leave the corporate kitchen and start fresh"},
            {"title": "Tampopo", "year": 1985, "reason": "Cooking as passion not pressure"},
            {"title": "Paterson", "year": 2016, "reason": "Finding art in everyday routine"},
            {"title": "Ponyo", "year": 2008, "reason": "Simple joyful Miyazaki magic"},
            {"title": "My Neighbor Totoro", "year": 1988, "reason": "Rest and wonder in the countryside"},
            {"title": "The Beach", "year": 2000, "reason": "Drop everything and find paradise"},
            {"title": "Wild", "year": 2014, "reason": "Walking the PCT to find yourself again"},
            {"title": "Up in the Air", "year": 2009, "reason": "A life on the road unravels"},
            {"title": "The Truman Show", "year": 1998, "reason": "Walk out of the constructed life"},
            {"title": "Eat Pray Love", "year": 2010, "reason": "Year-long sabbatical across three countries"},
            {"title": "Captain Fantastic", "year": 2016, "reason": "Rejecting modern society for forest life"},
            {"title": "The Way", "year": 2010, "reason": "Walking the Camino de Santiago changes everything"},
            {"title": "A Good Year", "year": 2006, "reason": "Escape to a French vineyard to reset life"},
            {"title": "Under the Tuscan Sun", "year": 2003, "reason": "Buy a villa in Italy, rebuild your life"},
            {"title": "Sideways", "year": 2004, "reason": "Wine country road trip as therapy"},
        ],
        "series": [
            {"title": "The Midnight Gospel", "reason": "Trippy animated interviews about life and death"},
            {"title": "Detectorists", "reason": "The most gentle British show about metal detecting"},
            {"title": "The Good Place", "reason": "Philosophical comedy about what matters"},
            {"title": "Atlanta", "reason": "Slow burn creative journey"},
            {"title": "Somebody Somewhere", "reason": "Finding your people in middle America"},
        ],
    },
    "existential": {
        "name": "Existential Comfort",
        "emoji": "\U0001f30c",
        "description": "Big questions explored through beautiful stories",
        "movies": [
            {"title": "The Matrix", "year": 1999, "reason": "What is real? The question changes everything"},
            {"title": "Interstellar", "year": 2014, "reason": "Love transcends time and dimensions"},
            {"title": "2001: A Space Odyssey", "year": 1968, "reason": "Humanity's place in the cosmos"},
            {"title": "Arrival", "year": 2016, "reason": "Language shapes reality and time"},
            {"title": "The Tree of Life", "year": 2011, "reason": "The universe and a single family"},
            {"title": "Cloud Atlas", "year": 2012, "reason": "Our actions ripple across centuries"},
            {"title": "Blade Runner 2049", "year": 2017, "reason": "What makes us human?"},
            {"title": "Eternal Sunshine of the Spotless Mind", "year": 2004, "reason": "Memory and identity entwined"},
            {"title": "Synecdoche New York", "year": 2008, "reason": "Art imitates life imitates art"},
            {"title": "The Fountain", "year": 2006, "reason": "Love and death across time"},
            {"title": "Soul", "year": 2020, "reason": "Purpose isn't the point. Living is"},
            {"title": "Everything Everywhere All at Once", "year": 2022, "reason": "Multiverse as metaphor for existential overwhelm"},
            {"title": "Waking Life", "year": 2001, "reason": "A dream exploration of consciousness"},
            {"title": "Paprika", "year": 2006, "reason": "Dreams and reality collide"},
            {"title": "The Seventh Seal", "year": 1957, "reason": "Chess with death and the search for meaning"},
            {"title": "Donnie Darko", "year": 2001, "reason": "Time travel and teen existentialism"},
            {"title": "Her", "year": 2013, "reason": "Love and consciousness beyond the human"},
            {"title": "Coherence", "year": 2013, "reason": "Quantum mechanics and relationship drama"},
            {"title": "The Truman Show", "year": 1998, "reason": "What if your world is constructed?"},
            {"title": "Ikiru", "year": 1952, "reason": "What do you do with your remaining days?"},
        ],
        "series": [
            {"title": "Dark", "reason": "Time, fate, and free will in German sci-fi"},
            {"title": "The OA", "reason": "Near-death experiences and alternate dimensions"},
            {"title": "Severance", "reason": "Work-life balance taken to existential extremes"},
            {"title": "Westworld", "reason": "Consciousness and what it means to be real"},
            {"title": "True Detective S1", "reason": "Philosophical crime drama about time and meaning"},
        ],
    },
    "hope": {
        "name": "Hope Injection",
        "emoji": "\U0001f31f",
        "description": "Films that restore faith in humanity and the future",
        "movies": [
            {"title": "The Shawshank Redemption", "year": 1994, "reason": "Hope is a good thing, maybe the best of things"},
            {"title": "Life is Beautiful", "year": 1997, "reason": "Love protects innocence even in darkness"},
            {"title": "The Green Mile", "year": 1999, "reason": "Extraordinary kindness in ordinary places"},
            {"title": "Schindler's List", "year": 1993, "reason": "One person can make an impossible difference"},
            {"title": "Rudy", "year": 1993, "reason": "Dreams pursued against all odds"},
            {"title": "Rocky", "year": 1976, "reason": "It's not about winning. It's about going the distance"},
            {"title": "The Pursuit of Happyness", "year": 2006, "reason": "Homelessness to success through determination"},
            {"title": "It's a Wonderful Life", "year": 1946, "reason": "You are richer than you know"},
            {"title": "Billy Elliot", "year": 2000, "reason": "Dance against all expectations"},
            {"title": "The Boy Who Harnessed the Wind", "year": 2019, "reason": "Young ingenuity saves a village"},
            {"title": "Hidden Figures", "year": 2016, "reason": "Brilliant women who changed NASA"},
            {"title": "The Imitation Game", "year": 2014, "reason": "Alan Turing saved millions in secret"},
            {"title": "Slumdog Millionaire", "year": 2008, "reason": "Destiny and resilience in Mumbai"},
            {"title": "October Sky", "year": 1999, "reason": "Coal miner's son reaches for the stars"},
            {"title": "Freedom Writers", "year": 2007, "reason": "Education transforms lives"},
            {"title": "Remember the Titans", "year": 2000, "reason": "Football team unites a divided town"},
            {"title": "12 Years a Slave", "year": 2013, "reason": "The human spirit endures the unthinkable"},
            {"title": "Dangal", "year": 2016, "reason": "Indian father trains daughters to be champions"},
            {"title": "The Blind Side", "year": 2009, "reason": "One family's love changes a boy's future"},
            {"title": "Erin Brockovich", "year": 2000, "reason": "One woman takes on a corporation"},
        ],
        "series": [
            {"title": "Ted Lasso", "reason": "Pure optimism as a superpower"},
            {"title": "Anne with an E", "reason": "Imagination and resilience in a harsh world"},
            {"title": "The West Wing", "reason": "Idealistic look at government and good people"},
            {"title": "Queer Eye", "reason": "Transformation through kindness and style"},
            {"title": "Our Planet", "reason": "The world is beautiful and worth saving"},
        ],
    },
    "creativity": {
        "name": "Creative Spark",
        "emoji": "\U0001f4a1",
        "description": "Stories about art, creation, and finding your voice",
        "movies": [
            {"title": "Whiplash", "year": 2014, "reason": "The cost of artistic greatness"},
            {"title": "La La Land", "year": 2016, "reason": "Dreams and the sacrifices they demand"},
            {"title": "Amadeus", "year": 1984, "reason": "Genius, jealousy, and divine talent"},
            {"title": "Black Swan", "year": 2010, "reason": "Perfectionism in art destroys the artist"},
            {"title": "Birdman", "year": 2014, "reason": "An actor's desperate need for relevance"},
            {"title": "8 Mile", "year": 2002, "reason": "Rap battle as escape from poverty"},
            {"title": "Begin Again", "year": 2013, "reason": "Music created in the streets of New York"},
            {"title": "Almost Famous", "year": 2000, "reason": "Rock journalism and finding your voice"},
            {"title": "The Disaster Artist", "year": 2017, "reason": "So bad it's brilliant. Make your art anyway"},
            {"title": "Ed Wood", "year": 1994, "reason": "The worst director ever made movies with passion"},
            {"title": "Adaptation", "year": 2002, "reason": "Writer's block breaks the fourth wall"},
            {"title": "Big Eyes", "year": 2014, "reason": "A female artist finds her voice"},
            {"title": "Frida", "year": 2002, "reason": "Pain transformed into iconic art"},
            {"title": "Midnight in Paris", "year": 2011, "reason": "Nostalgia for creative eras past"},
            {"title": "Topsy-Turvy", "year": 1999, "reason": "Gilbert and Sullivan's creative process"},
            {"title": "The Diving Bell and the Butterfly", "year": 2007, "reason": "Creating art with only your eyelid"},
            {"title": "Coco", "year": 2017, "reason": "Music connects generations"},
            {"title": "Soul", "year": 2020, "reason": "Finding your spark vs your purpose"},
            {"title": "Sing Street", "year": 2016, "reason": "Start a band to impress a girl, find yourself"},
            {"title": "Tick Tick Boom", "year": 2021, "reason": "Rent creator's struggle before success"},
        ],
        "series": [
            {"title": "The Crown", "reason": "Duty and art in public service"},
            {"title": "Atlanta", "reason": "Music scene as a backdrop for surreal creativity"},
            {"title": "High Fidelity", "reason": "Record store owner's musical obsession"},
            {"title": "Mozart in the Jungle", "reason": "Behind the scenes of a symphony orchestra"},
            {"title": "Abstract: The Art of Design", "reason": "Documentary about creative minds at work"},
        ],
    },
    "scared": {
        "name": "Fear Tamer",
        "emoji": "\U0001f96f",
        "description": "Face your fears through stories of courage and resilience",
        "movies": [
            {"title": "Courage Under Fire", "year": 1996, "reason": "Facing fear with honor and duty"},
            {"title": "The Revenant", "year": 2015, "reason": "Survival against impossible odds"},
            {"title": "127 Hours", "year": 2010, "reason": "What would you do to survive?"},
            {"title": "Gravity", "year": 2013, "reason": "Alone in space, finding the will to live"},
            {"title": "Apollo 13", "year": 1995, "reason": "Houston we have a problem. Working through fear"},
            {"title": "Jaws", "year": 1975, "reason": "Fear of the unknown. Face it anyway"},
            {"title": "The Shining", "year": 1980, "reason": "Psychological fear and isolation"},
            {"title": "A Quiet Place", "year": 2018, "reason": "Protecting family in silence"},
            {"title": "Life of Pi", "year": 2012, "reason": "Surviving the Pacific with a tiger"},
            {"title": "The Impossible", "year": 2012, "reason": "A family survives the 2004 tsunami"},
            {"title": "Whiplash", "year": 2014, "reason": "Fear of failure as motivation"},
            {"title": "Maze Runner", "year": 2014, "reason": "Escape the maze. Face the unknown"},
            {"title": "Alien", "year": 1979, "reason": "Fear of the dark and the alien within"},
            {"title": "The Descent", "year": 2005, "reason": "Claustrophobic fear and female resilience"},
            {"title": "Room", "year": 2015, "reason": "Captivity and the courage to escape"},
            {"title": "The Pursuit of Happyness", "year": 2006, "reason": "Fear of homelessness drives determination"},
            {"title": "The Martian", "year": 2015, "reason": "Problem-solve your way through fear"},
            {"title": "Free Solo", "year": 2018, "reason": "Climbing El Capitan without ropes"},
            {"title": "The Edge", "year": 1997, "reason": "Wilderness survival and resourcefulness"},
            {"title": "Silence of the Lambs", "year": 1991, "reason": "Facing the monster to catch the monster"},
        ],
        "series": [
            {"title": "Stranger Things", "reason": "Kids facing supernatural fears together"},
            {"title": "The Walking Dead", "reason": "Fear and survival in a broken world"},
            {"title": "American Horror Story", "reason": "Stylized fear as entertainment"},
            {"title": "Black Mirror", "reason": "Fear of technology and the future"},
            {"title": "The Haunting of Hill House", "reason": "Grief and fear intertwined beautifully"},
        ],
    },
    "nostalgia": {
        "name": "Nostalgia Warmth",
        "emoji": "\U0001f3f3\ufe0f\u200d\U0001f308",
        "description": "Warm stories that remind you of simpler times and fond memories",
        "movies": [
            {"title": "The Sandlot", "year": 1993, "reason": "Childhood summers and baseball"},
            {"title": "Stand By Me", "year": 1986, "reason": "A journey along the railroad tracks of youth"},
            {"title": "E.T.", "year": 1982, "reason": "Childhood wonder and extraterrestrial friendship"},
            {"title": "The Goonies", "year": 1985, "reason": "Adventure with friends before growing up"},
            {"title": "Back to the Future", "year": 1985, "reason": "The ultimate time-travel nostalgia trip"},
            {"title": "Ferris Bueller's Day Off", "year": 1986, "reason": "The perfect day skipping school"},
            {"title": "The Breakfast Club", "year": 1985, "reason": "Saturday detention and unlikely connections"},
            {"title": "Sixteen Candles", "year": 1984, "reason": "Awkward teenage years remembered fondly"},
            {"title": "Dazed and Confused", "year": 1993, "reason": "The last day of school in 1976"},
            {"title": "American Graffiti", "year": 1973, "reason": "Cruising and rock n roll before college"},
            {"title": "Forrest Gump", "year": 1994, "reason": "A journey through American decades"},
            {"title": "Toy Story", "year": 1995, "reason": "Childhood toys and growing up"},
            {"title": "The Parent Trap", "year": 1998, "reason": "Summer camp and reunited families"},
            {"title": "Home Alone", "year": 1990, "reason": "Christmas childhood fantasy"},
            {"title": "Jumanji", "year": 1995, "reason": "Board game adventure from childhood"},
            {"title": "The Little Rascals", "year": 1994, "reason": "Childhood friendship and mischief"},
            {"title": "Hook", "year": 1991, "reason": "Neverland calls you back"},
            {"title": "Big", "year": 1988, "reason": "Wishing to be grown up and its consequences"},
            {"title": "The Princess Bride", "year": 1987, "reason": "Fairy tale that spans generations"},
            {"title": "Now and Then", "year": 1995, "reason": "Childhood friends reunite as adults"},
        ],
        "series": [
            {"title": "Stranger Things", "reason": "80s nostalgia wrapped in sci-fi mystery"},
            {"title": "Wonder Years", "reason": "Growing up in the late 60s"},
            {"title": "Friends", "reason": "90s nostalgia and found family"},
            {"title": "That 70s Show", "reason": "Nostalgic look at the disco era"},
            {"title": "The Fresh Prince of Bel-Air", "reason": "90s sitcom warmth and heart"},
        ],
    },
}
